---
# TODO: Support Ubuntu

- name: distribution | Check OS compatibility
  debug:
    msg="Error your os is might not be supported '{{ ansible_os_family }}'"
  failed_when: ansible_os_family not in workstation_check_supported_platform
  when: ansible_os_family not in workstation_check_supported_platform
  ignore_errors: yes

- name: distribution | Check your distribution
  debug:
     msg="Your distribution might not be supported. '{{ ansible_distribution }}'"
  changed_when: ansible_distribution not in workstation_check_supported_distribution
  when: ansible_distribution not in workstation_check_supported_distribution
