---

- name: encryption | Mac Run fdesetup status
  command:
    fdesetup status
  failed_when: False
  changed_when: False
  register: hd_encryption_mac
  when: ansible_distribution == 'MacOSX' and workstation_check_hd_encryption

- name: encryption | Mac Complain if hd encryption is not on
  debug:
     msg="Error You should enable Valut on your mac for security reasons"
  failed_when: hd_encryption_mac.stdout.find('Off') != -1
  ignore_errors: yes
  when: ansible_distribution == 'MacOSX' and workstation_check_hd_encryption and hd_encryption_mac.stdout.find('Off') != -1

- name: encryption | Linux run blkid on home
  command:
    blkid `df -P /home/ | tail -1 | cut -d' ' -f 1`
  failed_when: False
  changed_when: False
  register: hd_encryption_linux
  when: ansible_distribution == 'Linux' and workstation_check_hd_encryption

- name: encryption | Linux Complain if hd encryption is not on
  debug:
     msg="Error You should enable Valut on your mac for security reasons"
  failed_when: hd_encryption_linux.stdout.find('crypto') != -1
  ignore_errors: yes
  when: ansible_distribution == 'Linux' and workstation_check_hd_encryption and hd_encryption_linux.stdout.find('crypto') != -1